apiVersion: v1
kind: Service
metadata:
  name: aesthetic-service-staging
  namespace: aesthetic-hub-staging
  labels:
    app: aesthetic-service
    track: staging
spec:
  type: ClusterIP
  selector:
    app: aesthetic-service
    track: staging
  ports:
    - name: http
      port: {{ .Values.aestheticService.port }}
      targetPort: {{ .Values.aestheticService.port }}
{{- if .Values.triton.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-staging
  namespace: aesthetic-hub-staging
  labels:
    app: triton
    track: staging
spec:
  type: ClusterIP
  selector:
    app: triton
    track: staging
  ports:
    - name: http
      port: {{ .Values.triton.port }}
      targetPort: {{ .Values.triton.port }}
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: {{ .Values.triton.metricsPort }}
      targetPort: {{ .Values.triton.metricsPort }}
{{- end }}
