import { Kysely, sql } from 'kysely';

/**
 * Resize smart_search.embedding from vector(512) to vector(768)
 * to match ViT-L-14__openai CLIP model output.
 *
 * This drops and recreates the CLIP index since vector dimensions cannot
 * be altered in-place — the column must be recast.
 * All existing embeddings are cleared (they will be re-generated by the
 * machine-learning service on next smart-search job run).
 */
export async function up(db: Kysely<any>): Promise<void> {
  // Drop the existing CLIP vector index
  await sql`DROP INDEX IF EXISTS "clip_index";`.execute(db);

  // Truncate existing embeddings — they are 512-dim and incompatible
  await sql`TRUNCATE TABLE "smart_search";`.execute(db);

  // Alter column type to vector(768)
  await sql`ALTER TABLE "smart_search"
    ALTER COLUMN "embedding" TYPE vector(768)
    USING NULL;`.execute(db);

  // Recreate the index for the new dimension
  await sql`CREATE INDEX "clip_index"
    ON "smart_search" USING vchordrq (embedding vector_cosine_ops)
    WITH (options='
      residual_quantization = false
      [build.internal]
      lists = [1]
      spherical_centroids = true
      build_threads = 4
      sampling_factor = 1024
    ');`.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql`DROP INDEX IF EXISTS "clip_index";`.execute(db);
  await sql`TRUNCATE TABLE "smart_search";`.execute(db);
  await sql`ALTER TABLE "smart_search"
    ALTER COLUMN "embedding" TYPE vector(512)
    USING NULL;`.execute(db);
  await sql`CREATE INDEX "clip_index"
    ON "smart_search" USING vchordrq (embedding vector_cosine_ops)
    WITH (options='
      residual_quantization = false
      [build.internal]
      lists = [1]
      spherical_centroids = true
      build_threads = 4
      sampling_factor = 1024
    ');`.execute(db);
}
