apiVersion: v1
kind: Service
metadata:
  name: aesthetic-scoring-canary
  namespace: aesthetic-hub-canary
  labels:
    app: aesthetic-scoring
    track: canary
spec:
  type: ClusterIP
  selector:
    app: aesthetic-scoring
    track: canary
  ports:
    - name: http
      port: {{ .Values.scoringService.port }}
      targetPort: {{ .Values.scoringService.port }}
{{- if .Values.triton.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-canary
  namespace: aesthetic-hub-canary
  labels:
    app: triton
    track: canary
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.triton.metricsPort }}"
spec:
  type: ClusterIP
  selector:
    app: triton
    track: canary
  ports:
    - name: http
      port: {{ .Values.triton.port }}
      targetPort: {{ .Values.triton.port }}
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: {{ .Values.triton.metricsPort }}
      targetPort: {{ .Values.triton.metricsPort }}
{{- end }}
